name: Playbook
repository: https://github.com/playbook-ui/playbook-flutter

packages:
  - playbook**
  - examples/**

ide:
  intellij: true

command:
  version:
    linkToCommits: true

scripts:
  format: melos exec -- exec flutter format .

  analyze: melos exec -- exec flutter analyze .

  clean: melos exec -- exec flutter clean

  pub:upgrade:
    run: |
      melos exec -- exec flutter pub upgrade
      melos bootstrap

  pub:get:
    run: melos exec -- exec flutter pub get

  gen:build_runner:
    run: |
      melos exec -- exec flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: "build_runner"

  test:unit:
    run: |
      melos exec -- exec flutter test
    packageFilters:
      noDependsOn:
        - "playbook_snapshot"
      dirExists:
        - test

  test:snapshot:
    run: |
      melos exec -- exec flutter test --update-goldens
    packageFilters:
      dependsOn:
        - "playbook_snapshot"
      dirExists:
        - test

  test:snapshot:simple:
    run: |
      melos exec -- exec flutter test --update-goldens
    packageFilters:
      scope: "simple_catalog_app"
